/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nesneodev;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nesneodev.DataAccess.Arac;
import nesneodev.DataAccess.AracDataAccess;
import nesneodev.DataAccess.Depo;
import nesneodev.DataAccess.DepoDataAccess;
import nesneodev.DataAccess.Paket;
import nesneodev.DataAccess.PaketDataAccess;

/**
 *
 * @author Caglar
 */
public class Kargo extends javax.swing.JFrame {

    /**
     * Creates new form Kargo
     */
    public Kargo() {
        initComponents();
        AracDataAccess adc = new AracDataAccess();
        ArrayList<String> liste = new ArrayList<String>();
        try {
            liste = adc.AracGetir();
        } catch (IOException ex) {
            Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i=0; i<liste.size(); i++){
            jComboBox1.addItem(liste.get(i));
        }
        try {
            DepoPaketGetir();
        } catch (IOException ex) {
            Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_aracYukle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_depoCikar = new javax.swing.JButton();
        pnl_aracDetay = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_maxDesi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ozelDesi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_sigortaDesi = new javax.swing.JLabel();
        btn_yenile = new javax.swing.JButton();
        lbl_paketSayisi = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kargo Otomasyon");
        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paket Seri No", "Paket Tipi", "Paket İçeriği", "Desi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Araç Seçiniz : ");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btn_aracYukle.setText("Seçili Paketleri Araca Yükle");
        btn_aracYukle.setEnabled(false);
        btn_aracYukle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aracYukleActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Depodaki Paketler  :");

        btn_depoCikar.setText("Seçili Paketi Depodan Çıkar");
        btn_depoCikar.setEnabled(false);
        btn_depoCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depoCikarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Maksimum Desi  : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Özel Desi  : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sigortalı Desi  : ");

        javax.swing.GroupLayout pnl_aracDetayLayout = new javax.swing.GroupLayout(pnl_aracDetay);
        pnl_aracDetay.setLayout(pnl_aracDetayLayout);
        pnl_aracDetayLayout.setHorizontalGroup(
            pnl_aracDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aracDetayLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_maxDesi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ozelDesi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_sigortaDesi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );
        pnl_aracDetayLayout.setVerticalGroup(
            pnl_aracDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aracDetayLayout.createSequentialGroup()
                .addGroup(pnl_aracDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_maxDesi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_aracDetayLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_aracDetayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_sigortaDesi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ozelDesi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btn_yenile.setText("Yenile");
        btn_yenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenileActionPerformed(evt);
            }
        });

        jMenu1.setText("Depo");

        jMenuItem1.setText("Yeni Paket Ekle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleName("mn_yeniPaketEkle");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Araçlar");

        jMenuItem2.setText("Yeni Araç Ekle");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenuItem2.getAccessibleContext().setAccessibleName("mn_yeniAracEkle");

        jMenuItem5.setText("Aracı Sisteme Aktar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem3.setText("Araç Listesi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenuItem3.getAccessibleContext().setAccessibleName("mn_araclar");

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_depoCikar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aracYukle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(lbl_paketSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_yenile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnl_aracDetay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_aracDetay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_yenile)
                    .addComponent(jLabel2)
                    .addComponent(lbl_paketSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_depoCikar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_aracYukle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1134, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        YeniAracEkle aracEkle = new YeniAracEkle();
        aracEkle.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       AracListesi aracListe = new AracListesi();
       aracListe.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //TO:DO Seçilen araç plakasına ait araca yüklü karoları getir.
        String seciliPlaka = jComboBox1.getSelectedItem().toString();
        AracDataAccess ada = new AracDataAccess();
        try {
            Arac arac = ada.AracBilgiler(seciliPlaka);
            lbl_maxDesi.setText(Integer.toString(arac.MaxDesi));
            lbl_ozelDesi.setText(Integer.toString(arac.OzelDesi));
            lbl_sigortaDesi.setText(Integer.toString(arac.SigortaDesi));
        } catch (IOException ex) {
            Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_depoCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depoCikarActionPerformed
        
        int sonuc = JOptionPane.showConfirmDialog(null, "Seçili paketi/paketleri depodan çıkarmak istediğinizden emin misiniz?", "İşlem Onayla!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(sonuc == JOptionPane.YES_OPTION){
            try {
                DepoPaketCikar();
                DepoPaketGetir();
            } catch (IOException ex) {
                Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Seçili paket/ler depodan çıkarıldı.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_depoCikarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AracAktar aracAktar = new AracAktar();
        aracAktar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        YeniPaketEkle paketEkle = new YeniPaketEkle();
        paketEkle.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_yenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenileActionPerformed
        try {
            DepoPaketGetir();
            btn_depoCikar.setEnabled(false);
            btn_aracYukle.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_yenileActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        btn_depoCikar.setEnabled(true);
        btn_aracYukle.setEnabled(true);
    }//GEN-LAST:event_jTable1MousePressed

    private void btn_aracYukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aracYukleActionPerformed
        String plaka = jComboBox1.getSelectedItem().toString();
        Depo depo = new Depo();
        
        //Kullanıcının araca yüklemek istediği paketler.
        ArrayList<Paket> seciliPaketler = new ArrayList<Paket>();
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        int indis[] = jTable1.getSelectedRows();
        char tip, iceriktip;
        for(int i = indis.length - 1; i >= 0; i--){
            tip = (jTable1.getValueAt(indis[i], 1).toString() == "Posta" ? 'P' : (jTable1.getValueAt(indis[i], 1).toString() == "Küçük Paket") ? 'K' : (jTable1.getValueAt(indis[i], 1).toString() == "Büyük Paket") ? 'B' : 'S');
            iceriktip = (jTable1.getValueAt(indis[i], 2).toString() == "Normal Paket" ? 'N' : (jTable1.getValueAt(indis[i], 2).toString() == "Ticari Paket") ? 'T' : 'S');
            seciliPaketler.add(new Paket(jTable1.getValueAt(indis[i], 0).toString(), tip, iceriktip, Double.parseDouble(jTable1.getValueAt(indis[i], 3).toString())));
        }
        
        AracDataAccess ada = new AracDataAccess();
        try {
            int sonuc = JOptionPane.showConfirmDialog(null, "Seçili paketi/paketleri araca yüklemek istediğinizden emin misiniz?", "İşlem Onayla!!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
            if(sonuc == JOptionPane.YES_OPTION){
                if(ada.AracaPaketYukle(plaka, seciliPaketler)){
                    JOptionPane.showMessageDialog(null, "Seçili paket/ler " + plaka + " plakalı araca yüklendi.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
                    
                    int index[] = jTable1.getSelectedRows();
        
                    Arrays.sort(indis);

                    for(int i = indis.length - 1; i >= 0; i--){
                        model.removeRow(indis[i]);
                    }
                    lbl_paketSayisi.setText(jTable1.getRowCount() + " adet.");
                }else{
                    JOptionPane.showMessageDialog(null, "Seçili paketler araç kapasitesini aşıyor.", "Hata!!", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Kargo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aracYukleActionPerformed
    
    //Paketi depodan çıkarma ve değişikliklerin arayüze yansıtılması.
    private void DepoPaketCikar() throws IOException{
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        PaketDataAccess pda = new PaketDataAccess();
        
        int indis[] = jTable1.getSelectedRows();
        
        Arrays.sort(indis);
        
        ArrayList<String> paketler = new ArrayList<String>();
        
        for(int i = indis.length - 1; i >= 0; i--){
            paketler.add(jTable1.getValueAt(indis[i], 0).toString());
        }
        
        pda.PaketCikar(paketler);
        
        for(int i = indis.length - 1; i >= 0; i--){
            model.removeRow(indis[i]);
        }
        
        jTable1.clearSelection();
        btn_depoCikar.setEnabled(false);
        btn_aracYukle.setEnabled(false);
    }
    
    //Depodan paket çıkırılınca arayüzdeki tablodan silinmesi.
    private void DepoPaketGetir() throws IOException{
        DepoDataAccess dda = new DepoDataAccess();
        ArrayList<Paket> paketler = dda.DepoPaketler();
        
        if(paketler != null){
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            Object rowData[] = new Object[4];

            for(int i=0; i<paketler.size(); i++){
                rowData[0] = paketler.get(i).SeriNo;
                rowData[1] = (paketler.get(i).Tip == 'P' ? "Posta" : (paketler.get(i).Tip == 'K') ? "Küçük Paket" : (paketler.get(i).Tip == 'B') ? "Büyük Paket" : "Özel Gönderi"); 
                rowData[2] = (paketler.get(i).IcerikTip == 'N' ? "Normal Paket" : (paketler.get(i).IcerikTip == 'T') ? "Ticari Paket" : "Sigortalı Paket");
                rowData[3] = paketler.get(i).Desi;
                model.addRow(rowData);
            }
            
            lbl_paketSayisi.setText(paketler.size() + " adet.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kargo kg = new Kargo();
                kg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aracYukle;
    private javax.swing.JButton btn_depoCikar;
    private javax.swing.JButton btn_yenile;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_maxDesi;
    private javax.swing.JLabel lbl_ozelDesi;
    private java.awt.Label lbl_paketSayisi;
    private javax.swing.JLabel lbl_sigortaDesi;
    private javax.swing.JPanel pnl_aracDetay;
    // End of variables declaration//GEN-END:variables
}
